package com.example.english_learning_app

data class Poster(val imageId: Int, val title: String)
class PosterList{val list = arrayListOf(
    Poster(R.drawable.a, ""),
    Poster(R.drawable.b, ""),
    Poster(R.drawable.c, ""),
    Poster(R.drawable.d, ""),
    Poster(R.drawable.e, ""),
    Poster(R.drawable.f, ""),
    Poster(R.drawable.g, ""),
    Poster(R.drawable.h, ""),
    Poster(R.drawable.i, ""),
    Poster(R.drawable.j, ""),
    Poster(R.drawable.k, ""),
    Poster(R.drawable.l, ""),
    Poster(R.drawable.m, ""),
    Poster(R.drawable.n, ""),
    Poster(R.drawable.o, ""),
    Poster(R.drawable.p, ""),
    Poster(R.drawable.q, ""),
    Poster(R.drawable.r, ""),
    Poster(R.drawable.s, ""),
    Poster(R.drawable.t, ""),
    Poster(R.drawable.u, ""),
    Poster(R.drawable.v, ""),
    Poster(R.drawable.w, ""),
    Poster(R.drawable.x, ""),
    Poster(R.drawable.y, ""),
    Poster(R.drawable.z, ""),)}